### PR TITLE
Development changes from BlenderDMX

### PR DESCRIPTION
**Pull request by vanous**
I am bringing our changes from BlenderDMX here upstream. Please see the commit messages for details. One thing that i am not sure about is what is the best way of including all the helper functions. I did not like them to be expending the main parser part of the project, but i am not sure if pushing them out to the `utils` is the best solution either. I would appreciate your opinion on this.

The current BlenderDMX development is in the `mvr_import` branch here https://github.com/hugoaboud/blenderDMX/tree/mvr_import .

### CODE REVIEW

**Comment by jackdpage** [comment]
HI @vanous 
Thanks for your interest in the project and your improvements. As you can probably tell, I haven't had much time to do anything on this for the past couple of years :)
I can see you've forked under open-stage and it is probably the best place to continue maintenance. Maybe I'll have more time one day to take a look at it again. Would you like me to add you to the pygdtf entry in PyPI so you can upload any improvements there?

**Comment by vanous** [comment]
Hello @jackdpage ,

thank you for all your work on the pygdtf library. As we have been progressing with the BlenderDMX project, it was finally time to move it to it's own GH organization called [Open-Stage](https://github.com/open-stage/) to allow for better organizing and team access (based on GitHub repo access system). As BlenderDMX now also supports MVR import, i started [pymvr](https://github.com/open-stage/python-mvr) library, which is heavily based on your pygdtf design. The pymvr is in an early stage, although importing fixtures already works and is used by BlenderDMX. With the move of BlenderDMX to a separate org, it maked sense to add pymvr to it. At the same time, it just makes sense to also keep pygdtf in the same place so i forked the pygdtf, merged my development branch with work that went to support the BlenderDMX project and added a testing setup plus GH actions to run it (as per the now closed PRs here).

To be honest, i am not sure what this means in a long run :) , but i wanted to let you know about it. I have no idea what would be a good ownership model, as i myself am "only" a member in the Open-Stage org, @hugoaboud is the solely owner (which is fine for now). At this point, i have no plan to do any release of the updated pygdtf, as based on usage of our additions i feel that some of the current work might need adjusting, which could mean small breaking changes. Updating pygdtf to 1.2 is the longer term plan.

So, let me close this PR and please let me know what you think or if you have any proposals, ideas, objections...

Thank you, vanous

**Comment by vanous** [comment]
> Thanks for your interest in the project and your improvements. As you can probably tell, I haven't had much time to do anything on this for the past couple of years :)
> I can see you've forked under open-stage and it is probably the best place to continue maintenance. Maybe I'll have more time one day to take a look at it again. Would you like me to add you to the pygdtf entry in PyPI so you can upload any improvements there?

Hi @jackdpage , 
thank you for getting back and also thank you for the PyPi offer. Feel free to do so, I think it will make sense in the future. We can also wait with this for now and once there is enough to be published, i will let you know and may ask for being added...

**Comment by hugoaboud** [comment]
Hey @jackdpage, please let me know if you're interested in being added to the `open-stage` organization as a collaborator. I'm also out of time for coding such projects, but having more people on the organization encourages other people to join and sum forces.

**Comment by vanous** [comment]
Hi @jackdpage,

i have released [pymvr to pypi](
https://pypi.org/project/pymvr/) (MVR is GDTF's sister project) and i think i am ready to also publish updates to pygdtf. If you could please add me to pypi to the pygdtf project, thank you. There is still much work to do in the future, but there have been many improvements and I think it would be good to make sure people searching for latest version land on the continuation of the project... :)
Thank you!

**Comment by vanous** [comment]
Thank you!

**Pull request closed without merging**
